# Calendar outline

<iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;mode=WEEK&amp;height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;src=ohad.kammar%40gmail.com&amp;color=%234A716C&amp;src=qp9jlvsahulbpmqig5oeag9vrtmj3m8j%40import.calendar.google.com&amp;color=%232F6309&amp;ctz=Europe%2FLondon" style=" border-width:0 " width="800" height="600" frameborder="0" scrolling="no"></iframe>
