


<table border="0">
  <tr>
  <td style="vertical-align:top;width:50%;">

  <h3><a name="contact"></a>
  Contact
  </h3>
  Office 3.11                                     <br>
  [Bayes Centre](https://www.ed.ac.uk/bayes)      <br>
  [School of Informatics](https://www.inf.ed.ac.uk)<br>
  [University of Edinburgh](https://www.ed.ac.uk/) <br>
  47 Potterrow                                    <br>
  Edinburgh EH8 9BT                               <br>
  Tel:  +44 (0)131 (6) 50 2960                    <br>
  Post: ohad.kammar@ed.ac.uk                      <br>

  <br>
  To schedule an appointment, consult my [calendar](calendar.html).
  </td>
  <td style=horizontal-align:right>
  
  ![profile](ohad.jpg "meaningful thoughts...")
  </td>
  </tr>
  <tr>
    <td style="vertical-align:top;width:50%;">
### Current projects<a name="current_projects"></a>

I currently hold a [Royal Society](https://www.royalsociety.org/) [University Research Fellowship](https://royalsociety.org/grants-schemes-awards/grants/university-research/) on **effectful theories of programming languages: models, abstractions, validation, and axiomatics**.
Current and former project members are [Kasia Marek](https://www.inf.ed.ac.uk/people/staff/Katarzyna_Marek.html), [Justus Matthiesen](https://www.inf.ed.ac.uk/people/staff/Justus_Matthiesen.html),
[James McKinna](https://homepages.inf.ed.ac.uk/jmckinna/),
[Philip Saville](https://www.cs.ox.ac.uk/people/philip.saville/home.html), and
[Craig McLaughlin](https://www.unsw.edu.au/staff/craig-mclaughlin).

I am a co-investigator on **differentiable probabilistic programming semantics**, other project members are
[Luke Ong](https://www.cs.ox.ac.uk/people/luke.ong/),
[Sam Staton](https://www.cs.ox.ac.uk/people/samuel.staton/main.html),
[Matthijs Vákár](https://www.columbia.edu/~mv2745/),
[Maria I. Gorinova](https://homepages.inf.ed.ac.uk/s1207807/), and
[Jesse Sigal](), thanks to [Facebook Research](https://research.fb.com/).
The project is co-ordinated with [Erik Meijer](https://twitter.com/headinthebox),
[Satish Chandra](https://research.fb.com/people/chandra-satish/) at Facebook.

I am also involved with [Ehud Lamm](https://ehudlamm.com/)'s [Conceptual Biology Lab](https://ehudlamm.com/cbl.html).


### Past projects<a name="past_projects"></a>

* During 2021-2022 I was a principal investigator on **[type-driven data-science infrastructure for Idris2](https://vetss.org.uk/type-driven-data-science-infrastructure-for-idris2/)**, supported by the [National Cyber Security Centre (NCSC)](https://www.ncsc.gov.uk/) as part of the [UK Research Institute in Verified Trustworhy Software Systems](https://vetss.org.uk/). Project members were Robert Wright at the University of Edinburgh, [Edwin Brady](https://www.type-driven.org.uk/edwinb/) and [Guillaume Allais](https://gallais.github.io/) at the University of St Andrews, and [Jeremy Yallop](https://www.cl.cam.ac.uk/~jdy22/) at the University of Cambridge.

* During 2018-2019 I am worked with [Tom Melham](https://www.cs.ox.ac.uk/people/tom.melham/), [Sam Staton](https://www.cs.ox.ac.uk/people/samuel.staton/main.html), [Marcin Szymczak](https://moves.rwth-aachen.de/people/), [Helen Margetts](https://www.oii.ox.ac.uk/people/helen-margetts/), and [Scott Hale](https://www.oii.ox.ac.uk/people/scott-hale) on probabilistic programming in the social sciences thanks to the [Alan Turing Institute](https://www.turing.ac.uk/).

* During 2017-2018, I held a Career Development Felowship in **polymorphic effects** at [Balliol College Oxford](https://www.balliol.ox.ac.uk/).

* During 2016-2018 I worked with [Sam Staton](https://www.cs.ox.ac.uk/people/samuel.staton/main.html) on his [Royal Society-EPSRC funded project](https://gow.epsrc.ac.uk/NGBOViewGrant.aspx?GrantRef=EP/N007387/1) thanks to the [Engineering and Physical Sciences Research Council](https://www.epsrc.ac.uk/) and the [Royal Society](https://royalsociety.org/).

* During 2014-2016 I worked with [Glynn Winskel](https://www.cl.cam.ac.uk/~gw104/) on [Events, Causality and Symmetry --- the next generation semantics](https://www.cl.cam.ac.uk/~gw104/ECSYM-ScientificProposal.pdf) thanks to the [European Research Council](https://erc.europa.eu/).


* During 2013-2014 I worked with [Peter Sewell](https://www.cl.cam.ac.uk/~pes20/) on [Semantic Foundations for Real-World Systems](https://gow.epsrc.ac.uk/NGBOViewGrant.aspx?GrantRef=EP/H005633/1), with close interaction with the participants of [Rigorous Engineering for Mainstream Systems](https://www.cl.cam.ac.uk/~pes20/rems/) thanks to the [Engineering and Physical Sciences Research Council](https://www.epsrc.ac.uk/).

* During 2012-2013 I worked with [Sam Staton](https://www.cs.ox.ac.uk/people/samuel.staton/main.html) on **algebraic theories, computational effects, and concurrency,** thanks to the [Isaac Newton Trust](https://www.newtontrust.cam.ac.uk/).

* During 2009-2013 I worked with [Gordon D. Plotkin](https://www.homepages.inf.ed.ac.uk/gdp/) on my PhD thesis **[an algebraic theory of type and effect systems](thesis)**, thanks to the [Scottish Informatics and Computer Science Alliance](https://www.sicsa.ac.uk/) and the [University of Edinburgh Informatics Graduate School](https://www.inf.ed.ac.uk/student-services/graduate-school/).


</td>
  <td style="vertical-align:top; width:50%;">
### Research interests<a name="interests"></a>
* Applied mathematics
    * Category theory
    * Logic
      * Ordinal notation systems
    * Universal algebra

* Programming language theory
    * Semantics, in particular denotational semantics
    * Expressivity
    * Polymorphism
        * Value restriction
    * Computational effects
        * Effect type systems
        * Effect handlers
        * Delimited control
        * Monadic reflection
    * Domain theory
        * Axiomatisation
        * Probabilistic powerdomains
        * Jung-Tix problem
    * Probabilistic programming
        * Semantics
        * Structuring generative models
        * Variational inference and kernel methods
    * Concurrency
        * Event structures
        * Relaxed behaviour
    * Access control
    * Staging and metaprogramming
        * Partially-static data structures
        
* Conceptual biology
    * Coevolution
    * Drift
    * The Baldwin effect
</tr>
</table>

### Publications and preprints ([abstracts](talks-and-publications.html#publications))<a name="pubs"></a>
$pubs:shortOutput()$


### [Teaching](teaching/index.html) ([Part III/Mphil projects](teaching/partIII.html), [Part II projects](teaching/partII.html), [Courses](teaching/index.html))


### Talks ([abstracts](talks-and-publications.html#talks))<a name="talks"></a>
$talks:shortOutput()$

### Reports ([abstracts](talks-and-publications.html#reports))<a name="reports"></a>
$other:shortOutput()$

### Upcoming gigs<a name="gigs"></a>
$future:shortOutput()$

### Community service<a name="services"></a>

2022

* Thanks to [Christine Tasson](https://www-apr.lip6.fr/~tasson)'s valiant efforts, we now have a digital copy of [Yves Lafont](https://www-apr.lip6.fr/~tasson/doc/reading/Yves_Laffont_phd.pdf)'s thesis.
  This liberation mission was initiated by [Philip Saville](https://philipsaville.co.uk/) with the moral support of [James McKinna](https://researchportal.hw.ac.uk/en/persons/james-mckinna).

2020

* [Sam Staton](https://www.cs.ox.ac.uk/people/samuel.staton/main.html) succeeded, where I failed, to liberated Johan Joss's PhD thesis [Algorithmisches Differenzierens](https://www.research-collection.ethz.ch/handle/20.500.11850/134597) from the trees. This effort was inspired by a talk given by [Michele Pagani](https://www.irif.fr/~michele/index.html).

* Liberated Rod Burstall's [Writing search algorithms in functional form](scans/burstall-writing-search-algorithms-in-functional-form.pdf) from the trees.   
  This deed was made possible with the kind help of [Daniel Hillerström](https://www.dhil.net/).
  <BR/>
  Full citation:
  <BR/>
  Burstall, R.M.: Writing search algorithms in functional form. In: Michie, D. (ed.) Machine Intelligence, vol. 3, pp. 373–385. Edinburgh University Press (1968).
  <BR/>
  The original copy did not have a copyright notice. If you are aware of this copy infringing on a copyright, please get in touch.




* PC member, 5th International Conference on Formal Structures for Computation and Deduction (FSCD 2020), which will take place in Paris (France), June/July, 2020. Submit a paper!

* PC Co-chair, [Languages for Inference (LAFI, né PPS)](https://popl19.sigplan.org/track/lafi-2019), with [Dougal Maclaurin](https://dougalmaclaurin.com/). [Submit](https://lafi20.hotcrp.com/) a talk proposal!

* PC member, ACM SIGPLAN Symposium on Principles of Programming Langages (POPL 2020). Submit a paper!

2019

* Co-organise the [International Summer School on Metaprogramming](https://www.cl.cam.ac.uk/events/metaprog/2019/) at [Schloss Dagstuhl](https://www.dagstuhl.de/en/program/calendar/evhp/?semnr=19333) with [Dr. Jeremy Yallop](https://www.cl.cam.ac.uk/~jdy22/) and [Prof. Yukiyoshi Kameyama](https://www.cs.tsukuba.ac.jp/~kam/logic.cs.tsukuba.ac.jp/~kam/). [Registration](https://www.cl.cam.ac.uk/events/metaprog/2019/application.html) is now open!

* External reviewing committee, [24th ACM SIGPLAN International Conference on Functional Programming](https://conf.researchr.org/signup/icfp-2019). Submit a paper!

* PC member, Asian Symposium on Programming Languages and Systems (APLAS 2019). Submit a paper!

* PC Co-chair, [Languages for Inference (LAFI, né PPS)](https://popl19.sigplan.org/track/lafi-2019), with [Jeffery Siskind](https://engineering.purdue.edu/~qobi/). [Submit](https://lafi19.hotcrp.com/) a talk proposal!

* [Committee member](https://royalsociety.org/people/ohad-kammar-13862/), [Royal Society](https://www.royalsociety.org) [International Exchanges](https://royalsociety.org/grants-schemes-awards/grants/international-exchanges/) [Committee](https://royalsociety.org/about-us/committees/international-exchanges-committee/), 2019-2021. 

2018

* PC member, [34th Conference on the Mathematical Foundations of
  Programming Semantics (MFPS)
  2018](https://www.mathstat.dal.ca/mfps2018/). [Submit](https://easychair.org/conferences/?conf=mfps34)
  a paper!

* PC Co-chair, [Workshop on Syntax and Semantics of Low-Level Languages
  (LOLA'18)](https://cs.appstate.edu/~johannp/lola18/), with [Prof. Patricia
  Johann](https://cs.appstate.edu/~johannp/). [Submit](https://easychair.org/conferences/?conf=lola2018) an abstract! :)

* PC member, [Workshop on Probabilistic Programming Languages, Semantics, and Systems](https://conf.researchr.org/track/pps-2018/pps-2018).

2017

* Student Bursary Chair, [Second International Conference on Formal
  Structures for Computation and Deduction
  (FSCD'17)](https://www.cs.ox.ac.uk/conferences/fscd2017/registration.html).

* PC member, Workshop on [Syntax and Semantics of Low-Level Languages (LOLA'17)](https://events.cs.bham.ac.uk/lola2017/).

* Co-organise the [fifth South-Regional English Programming Language Seminar (S-REPLS)](./s-repls-5/) with [Prof Jeremy Gibbons](https://www.cs.ox.ac.uk/people/jeremy.gibbons/) and [Dr. Sam Staton](https://www.cs.ox.ac.uk/people/sam.staton/).

2016

* Co-organised the [International Summer School on Metaprogramming](https://www.cl.cam.ac.uk/events/metaprog2016/) with [Dr. Jeremy Yallop](https://www.cl.cam.ac.uk/~jdy22/) and Ms. Gemma Gordon.

2015 - 2018

* Co-founder and steering committee member of the [South-Regional English Programming Language Seminar (S-REPLS)](https://dominic-mulligan.co.uk/?page_id=148) with [Dr. Dominic Mulligan](https://dominic-mulligan.co.uk/) and [Dr. Jeremy Yallop](https://www.cl.cam.ac.uk/~jdy22/).

2014

* PC member, 3rd [ACM](https://www.acm.org) [SIGPLAN](https://www.sigplan.org/) Workshop on [Higher-Order
  Programming with Effects (HOPE'14)](https://www.mpi-sws.org/~neelk/hope2014/).

2013

* Liberated Robin Gandy's thesis [On Axiomatic Systems in Mathematics and Theories in Physics](https://www.repository.cam.ac.uk/handle/1810/245090) ([OCR](scans/gandy-thesis-ocr.pdf)) from the trees.   
  This deed was made possible with the kind help of [Martin
  Hyland](https://www.dpmms.cam.ac.uk/~martin/), the eager consent of
  the copyright holder, the literary executor [Mike
  Yates](https://pages.bangor.ac.uk/~mas041/index.html), and the
  generous financial support of [Barry
  Cooper](https://www.amsta.leeds.ac.uk/~pmt6sbc).
  <BR>
  [Nachum Dershowitz](https://www.cs.tau.ac.il/~nachumd/Homepage.html) supplied the [OCR](scans/gandy-thesis-ocr.pdf) version.

* Co-organised the [Haskell Symposium's](https://www.haskell.org/haskell-symposium/2013/) ``[Future of effects in Haskell](foeh/abstract.html)'' panel with [Sam Lindley](https://homepages.inf.ed.ac.uk/slindley/). 

* Co-organised the [Agda Course](agda-course-13/) in Cambridge with
  [Dr. Dominic Orchard](https://www.cl.cam.ac.uk/~dao29/).

* Liberated [algebra valued functors in general and tensor products in particular](scans/freyd-algebra-valued-functors-in-general-and-tensor-products-in-particular.pdf) by Prof. Peter Freyd from the trees.   
  I was unable to obtain Prof. Freyd's permission to put this scan up,
  but the book that included it did not contain any copyright
  notice. If you know I am infringing on his copyright, please let me
  know.

2011

* Liberated [Algebraic Theories (1969)](scans/wraith-algebraic-theories.pdf) by [Prof. Gavin Wraith](https://www.wra1th.plus.com) from the trees.  
  With the kind permission of Prof. Wraith, this scan of his Aarhus University Lecture Notes can be freely circulated.
  A [2-upped version](scans/wraith-algebraic-theories-double.pdf).
* Organised the [SICSA Agda Course](agda-course/) by [Conor McBride](https://www.cis.strath.ac.uk/cis/staff/index.php?uid=conor).

### Media presence<a name="media"></a>
* Interviewed for the [Edinbugh University](https://www.ed.ac.uk) [Informatics School](https://www.inf.ed.ac.uk) [CompuCast PodCast](https://computersciencepodcast.com/) "[Semantics, Semantics, Semantics](https://computersciencepodcast.com/download-mp3/23/23-episode.mp3)", November 2012.

### Consultancy services<a name="media"></a>
I provide private consultancy services at a limited capacity, separate
from my role at the University. I am also able to offer more extensive
consultancy services through the University.
