
-------------------------------------------

Subject: S-REPLS-5 contributed talk notification

Dear $it.speaker$,

Thank you for proposing to contribute the talk "$it.title$" for the fifth
S-REPLS meeting to take place in Oxford on 12 January 2017.

We are happy to be able to offer you a $if(it.length)$$it.length$$else$25$endif$ min slot, which
includes a short questions-and-answers session following your talk.

If you are _not_ able to accept due to changed circumstances, please
let Ohad know immediately, as we would otherwise assume your circumstances
have not changed.

If you require any additional equipment beyond a projector and two
large whiteboards, please let Ohad know as soon as possible.

Please see the S-REPLS-5 website for additional information about the
meeting:

http://www.cs.ox.ac.uk/people/ohad.kammar/s-repls-5/

We look forward to seeing you in January,

Ohad Kammar, <BR>
Sam Staton, and <BR>
Jeremy Gibbons.

<P>

