Teaching
========

Teaching in Cambridge is a privilege both stimulating and
enjoyable. I usually use my teaching roles to tie cutting-edge
research to the broader computer science subject, and to make this
material accessible and interesting for students.

### Courses

I am involved with teaching the following courses:

#### Undergraduate

* Part IA, [Discrete
  mathematics](http://www.cl.cam.ac.uk/teaching/1415/DiscMath/). Co-developed
  with [Prof. Marcelo Fiore](http://www.cl.cam.ac.uk/~mpf23/) the course
  materials ([slides
  (2013-14)](http://www.cl.cam.ac.uk/teaching/1314/DiscMath/DiscMathNotes.pdf),
  [workouts](http://www.cl.cam.ac.uk/teaching/1314/DiscMath/DiscMathWorkouts.pdf),
  [exercise
  sheets](http://www.cl.cam.ac.uk/teaching/1314/DiscMath/DiscMathExerciseSets01-11.pdf),
  and their example solutions), and I supervise this course.

* Part II, [Types](http://www.cl.cam.ac.uk/teaching/1415/Types/). Supervisor.

* Part II, [Denotational
  semantics](http://www.cl.cam.ac.uk/teaching/1415/DenotSem/). I
  developed an [exercise
  sheet](../teaching/ds-exercises.pdf)
  used for supervision work by myself and some of the
  [Lab](http://www.cl.cam.ac.uk/)'s supervisors.

#### Part III/MPhil

* [Advanced Topics in Denotational
  Semantics](http://www.cl.cam.ac.uk/teaching/1415/L29/).
  [Prof. Marcelo Fiore](http://www.cl.cam.ac.uk/~mpf23/) and myself will be offering this new course aimed to
  bring students up to date with active research in denotational
  semantics.


###[Part III/MPhil project suggestsions](partIII.html)

###[Part II project suggestsions](partII.html)

### Past students

#### Part II students

* 2014, Chris Kitching, Part II project "Source-Level Compile-Time Optimisations For Java". 

* 2014, reading group on recursive domain equations (following [these notes](../rdes/rde-intro.pdf))
    * Alex Chadwic
    * Adam Ścibior

    Surprisingly, while reading we found something new about
    ω-colimits of embedding-projection pairs, which will be
    [presented](../drafts/kammar-locally-determined-colimits.pdf) at the [11th
    international workshop on domain theory and
    applications](http://www.pps.univ-paris-diderot.fr/~varacca/domains/Domains_XI/Home.html). 
