<img src="GAF-Merton-Sunrise-Steve-Langton-GPC.jpg" title="Merton College Oxford, for illustration purposes only, taken from: http://www.ox.ac.uk/sites/files/oxford/styles/ow_large_feature/public/field/field_image_main/GAF%20Merton%20Sunrise%20Steve%20Langton%20GPC.jpg?itok=anwpyHY8 " style="width: 400px;"/>

<h1>The 5th [Southern-Region English Programming Language Seminar (S-REPLS)](http://dominic-mulligan.co.uk/?page_id=148)</h1>
<h2>Abstracts</h2>

<ul>
$talks:sReplsLong()$
</ul>
