<img src="GAF-Merton-Sunrise-Steve-Langton-GPC.jpg" title="Merton College Oxford, for illustration purposes only, taken from: http://www.ox.ac.uk/sites/files/oxford/styles/ow_large_feature/public/field/field_image_main/GAF%20Merton%20Sunrise%20Steve%20Langton%20GPC.jpg?itok=anwpyHY8 " style="width: 400px;"/>

<h1>The 5th [Southern-Region English Programming Language Seminar (S-REPLS)](http://dominic-mulligan.co.uk/?page_id=148)</h1>

* When: 11am-5pm, Thursday, 12th January 2017 (Thursday before [POPL](http://conf.researchr.org/home/POPL-2017))
* Where: Lecture Theatre B, Wolfson Building, [University of Oxford Department of Computer Science](http://www.cs.ox.ac.uk/) ([directions](http://www.cs.ox.ac.uk/aboutus/directions.html))
* The event is free of charge (coffee and refreshements provided)
* [Doodle registration: http://doodle.com/poll/hz6z3zqpupds2fm4](http://doodle.com/poll/hz6z3zqpupds2fm4)

S-REPLS is a regular informal meeting for those with a professional
interest in programming languages in the South of England region. The
past four meetings consisted of 50-90 participants from academia and
industry with invited and contributed talks ranging from abstract
areas in semantics and type system theory to nuts-and-bolts
implementations of mainstream and avant-garde compilers and
programming languages.

We will hold the next meeting at the University of Oxford Department
of Computer Science.

The meeting will take place between 11.00-17.00 on Thursday, 12th
January 2017, i.e., the Thursday before
[POPL](http://conf.researchr.org/home/POPL-2017).

Schedule ([Abstracts](abstracts.html))
====================
$schedule:sReplsShort()$

[Sign-up](http://doodle.com/poll/hz6z3zqpupds2fm4)
==================================================


The meeting is free of charge, but for logistical purposes please
indicate on [this Doodle
poll](http://doodle.com/poll/hz6z3zqpupds2fm4) if you plan to attend.

[http://doodle.com/poll/hz6z3zqpupds2fm4](http://doodle.com/poll/hz6z3zqpupds2fm4)



<A NAME="local"></A>Local information
=====================================

<iframe  float="right" src="https://www.google.com/maps/d/embed?mid=1YQDVylenG8Og5yjaunr73iLYvBw&hl=en" width="800" height="480"></iframe>
<br />

For directions to the [University of Oxford Department of Computer
Science](http://www.cs.ox.ac.uk/), see the [Department's directions
page](http://www.cs.ox.ac.uk/aboutus/directions.html)).

Lunch and dinner will **not** be provided.

For lunch, there are many restaurants
and/or take-away options in the [vicinity of the
Department](https://goo.gl/maps/kaNKTuYvMjE2). Alternatively, if you
are arriving from the train station or bus station, you can grab a
sandwhich on your way to the department.

* **Pub**: After the talks, we will continue more informal
    conversations at the [Red Lion](https://www.redlionoxford.co.uk),
    which is a short walk from the Department towards the central bus
    and train station which has some light dinner option.

* **Dinner**: After the pub, we will go to the [Turtle
    Bay](https://www.turtlebay.co.uk/food-drink/), around the corner
    from the pub.

    If you are pressed for time for dinner, or want to get your food
    earlier, or just want to make the chef less stressed, please
    **preorder** by emailing your food order to [Ohad Kammar &lt;ohad
    . kammar (at) cs ox ac uk&gt;](mailto:ohad.kammar@cs.ox.ac.uk) by
    **Wednesday evening**.


Mailing list
============

All S-REPLS related communications are made via the mailing list:

  [http://www.jiscmail.ac.uk/srepls](http://www.jiscmail.ac.uk/srepls)

This mailing list has very low traffic. If you have professional
interests in programming language in the region, we encourage you to
sign up.

Sponsorship
===========

Please let us know of potential sponsorship opportunities at:

[Ohad Kammar &lt;ohad . kammar (at) cs ox ac uk&gt;](mailto:ohad.kammar@cs.ox.ac.uk)

Past events have had academic, industrial, and government sponsorship
for invited speaker costs, and/or catering costs (lunch, dinner, or
refreshments during the break).


Organising future meetings
==========================
If you would like to organise future meetings at your university or
company, please get in touch with the [steering committee](http://dominic-mulligan.co.uk/?page_id=148):

+ [Dominic Mulligan](mailto:dpm36@cam.ac.uk)
+ [Jeremy Yallop](mailto:jeremy.yallop@cl.cam.ac.uk)
+ [Ohad Kammar](mailto:ohad.kammar@cs.ox.ac.uk)


We would be grateful if you could please circulate this event
in your department/company.


We hope to see you there,

+ Jeremy Gibbons,
+ Sam Staton,
+ and Ohad Kammar.


