<A HREF="quantum-day-2017.jpg"><img src="thumb.quantum-day-2017.jpg" title="Last year's Quantum Group Workshop (2017)" style="width: 400px;"/></A>

<h1>[Quantum Group](http://www.cs.ox.ac.uk/activities/quantum/) Workshop 2018</h1>

* When: 10am-5pm, Tuesday, 19th June 2018 
* Where: Lecture Theatre B, Wolfson Building, [University of Oxford Department of Computer Science](http://www.cs.ox.ac.uk/)

Schedule 
====================
$schedule:quantumWorkshop()$

<A NAME="local"></A>Bob's place
=====================================
For those who haven’t been there yet, it's 108 Kennington Rd., and you can either cycle, take taxi, walk, or take [bus 35 from St Aldates](https://city.oxfordbus.co.uk/timetables-fares/city35).


We hope to see you there,

Marietta, Ohad, Stefano and Subhayan

