*[LFCS](http://www.lfcs.inf.ed.ac.uk/), [University of
Edinburgh](http://www.ed.ac.uk/) presents:*   

# Introduction to Dependently Typed Programming using Agda
## [Conor McBride](http://www.cis.strath.ac.uk/cis/staff/index.php?uid=conor)
*[MSP](http://www.msp.cis.strath.ac.uk/), [University of Strathclyde](http://www.strath.ac.uk/)*

Types guarantee properties of runtime behaviour.  *Dependent types* give
stronger guarantees based on runtime values.  In this course we shall
introduce dependently typed programming using the Agda programming
language.  

The course consists of five weekly afternoon  sessions with
lectures and hands-on laboratories.  Exercises between sessions will
be set.  Refreshments will be provided during breaks.

<B>Prerequisites:</B> This is a research level course. We assume basic
 familiarity with a functional programming language, such as Haskell
 or ML, in particular pattern matching and higher-order functions like
 map.

This course is supported by the [Scottish Informatics and
Computer Science Alliance](http://www.sicsa.ac.uk/).

<B>Location:</B> 

- Lab sessions will be held in lab <B>4.12, Appleton Tower</B>.
- Lectures will take place in rooms <B>G.03 or G.07A, Informatics
  Forum</B>.  See below.

<B>Dates:</B>  Mondays, January 31, 2011 - February 28, 2011.

<B>Registration:</B> Please let us know you are coming so we can prepare
accordingly: <table border="0" cellpadding="0"
cellspacing="0"><tr><td>Ohad Kammar &nbsp;\<</td><td>ohad.kammar</td><td>@</td><td>ed.ac.uk&gt;</td></tr></table>

<B>Course Material:</B> All course material will be available online.
Conor has set up a darcs repository that contains everything available
currently.  You can grab it from:

		darcs get http://personal.cis.strath.ac.uk/~conor/pub/dtp

<B>Mailing List:</B> Course announcements, discussions and questions are welcome in the [agda-course mailing list](http://lists.inf.ed.ac.uk/mailman/listinfo/agda-course).  Non registrants are welcome as well.

<B>Schedule:</B>

$schedule:schedule()$

<B>Past Lectures:</B>

$pastlects:lecture()$

<B>Upcoming Lectures:</B>

$uplects:lecture()$

