<h1>An introduction to statistical modelling semantics with higher-order measure theory</h1>
<h3> [SPLV: The 4th Scottish Programming Languages and Verification Summer School](https://www.macs.hw.ac.uk/splv/splv-2022/) </h3>
<h4> [Ohad Kammar](http://www.denotational.co.uk)   11-16 July 2022</h4>

The last few years have seen several breakthroughs in the semantic
foundations of statistical modelling. In this course, I will
introduce one of these approaches --- quasi-Borel spaces.  We will
review and develop a semantic tool-kit for measure theory using
higher-order functions. The course will be accompanied by exercises
and tutorials, allowing you to develop a working knowledge and hands-on
experience.

<h3>Course materials</h3>

<h4> [Slides](../talks/2022-splv-higher-order-measure-theory.pdf)</h4>
<ul>
  <li/> [All slides (updated with corrections)](../talks/2022-splv-higher-order-measure-theory.pdf)</h4>
  <li/> [Lectures 1-2](../talks/2022-splv-higher-order-measure-theory-lectures-1-2.pdf) (video unavailable unfortunately)
  <li/> [Lectures 3-4](../talks/2022-splv-higher-order-measure-theory-lectures-3-4.pdf) ([video](https://www.youtube.com/watch?v=b1jIlQwG2gM&feature=emb_imp_woyt))
</ul>
See the [Marseille course](qbs-splv-2022/index.html#marseille) for additional content and videos.

<h4> [Exercise sheet (under development)](../qbs-splv-2022/marseille-notes-exercises.pdf)</h4>
  <ul>
  <li/> Context and background
  <br/>
  Doing all of these exercises is too much for the course, the goal is
  to learn something new, or --- if you already know this material ---
  help someone else learn something new.
  <ul>
    <li/> [Borel set basics](../qbs-splv-2022/marseille-notes-exercises-section-borel.pdf): introductory exercises if you've never worked with Borel sets, or looking for a refresher.
    <li/> [Measurable spaces and functions](../qbs-splv-2022/marseille-notes-exercises-section-measurable-spaces.pdf): exercises exploring the structure of measurable spaces and measurable functions.
    <li/> [Basic category theory](../qbs-splv-2022/marseille-notes-exercises-section-cats.pdf): use these exercises to improve your category theory.     <li/> [Aumann's theorem](../qbs-splv-2022/marseille-notes-exercises-section-aumann.pdf): consequences of and related concepts to Aumann's theorem on the inexistence of measurable function-spaces.
    <li/> [Sequences](../qbs-splv-2022/marseille-notes-exercises-section-sequences.pdf): examples of higher-order measure theory using sequences.
  </ul>
  <li/> An introduction to Quasi-Borel spaces
  <ul>
    <li/> [Quasi-Borel spaces](../qbs-splv-2022/marseille-notes-exercises-section-qbs-basics.pdf): first acquaintance with quasi-Borel spaces.
    <li/> [Qbs construction](../qbs-splv-2022/marseille-notes-exercises-section-qbs-constructions.pdf): space combinators --- you may want to spread these exercises over several sittings.
    <li/> [Borel subspaces](../qbs-splv-2022/marseille-notes-exercises-section-subspaces.pdf): measurable subsets in a quasi-Borel space.
  </ul>
  <li/> Measurability by type
  <ul> 
    <li/> [Function spaces](../qbs-splv-2022/marseille-notes-exercises-section-qbs-function-spaces.pdf): practice the definition of the function space of two qbses, with the Borel subsets and random element spaces.
    <li/> [Type structure](../qbs-splv-2022/marseille-notes-exercises-section-type-structure.pdf): use type-formers to put spaces together and form more complex spaces.
    <li/> Standard Borel spaces (under development): use measurability-by-type to construct standard Borel spaces.
  </ul>
  <li/> Measures and integration (under development)
  <ul>
  <li/> Measures: introductory exercises if you've never worked with measures before.
  <li/> Lebesgue integration: the definition of the Lebesgue integral.
  <li/> Randomisable measures: the class of measures we will work with.
  </ul>
  <li/> Kolmogorov's conditional expectation (under development)
  <ul> 
  <li/> Random variable spaces: definition and basic properties of the Lebesgue spaces.
  <li/> Geometry of random variable spaces: basic geometric and topological properties of Lebesgue spaces.
  <li/> Conditional expectation: existence and almost-certain uniqueness of Kolmogorov's conditional expectation.
  </ul>
  <li/> Extra-curricular material
  <ul>
    <li/> [More on the Borel hierarchy](../qbs-splv-2022/marseille-notes-exercises-section-borel-hierarchy.pdf): a guided tour of the proof of Aumann's theorem.
    <li/> [Aumann's theorem for Lebesgue measurablity](../qbs-splv-2022/marseille-notes-exercises-section-lebesgue-measurability.pdf): extending Aumann's theorem from Borel measurable functions to Lebesgue measurable functions.
  </ul>
</ul>

<h4 id="marseille">Previous instances</h4>
You can see a previous iteration of this course, given as part of the [Logic of Probabilistic Programming](https://cirmbox.cirm-math.fr/s/gm7FQRrqsNNjG8p) conference in 2022:
<ul>
<li/> Videos: [lecture 1](https://library.cirm-math.fr/Record.htm?idlist=3&record=19289752124910079349), [lecture 2](https://cirmbox.cirm-math.fr/s/gm7FQRrqsNNjG8p)
<li/> [Slides](../talks/2022-cirm-higher-order-measure-theory.pdf)
</ul>
